title: VerCors Tool FMT | Utwente
baseurl: /vercors
markdown: kramdown
kramdown:
  footnote_backlink: '&#x21a9;&#xfe0e;'
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

plugins: [jekyll-paginate]

paginate: 5
paginate_path: '/news/page-:num/'
